[package]
name = "piptable-dag"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
piptable-primitives = { workspace = true }
thiserror = { workspace = true }
