[package]
name = "piptable-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
piptable-primitives = { path = "../primitives" }
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]