[package]
name = "piptable-formatting"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
chrono = { workspace = true }
piptable-primitives = { workspace = true }

[lints]
workspace = true
